version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: argo
      POSTGRES_USER: argo
      POSTGRES_PASSWORD: argo
    ports:
      - "5432:5432"
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
  fastapi:
    build: .
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://argo:argo@db:5432/argo
      - CHROMA_URL=http://chroma:8000
    depends_on:
      - db
      - chroma
